### PR TITLE
Fix/handle GitHub fetch errors

### LINKED ISSUE #28: Person details: if github username is wrong fails silently
Currently if somebody deletes his github username or change it when we hit the github api the call fails without feedback to the users. We need proper feedback to the users.

### PR DESCRIPTION
**Pull request by lordfuoco**
fixes #28

### CODE REVIEW

File: frontend/components/RepositoryList.vue [hunk 1]
```diff
@@ -10,13 +10,26 @@
...
       </v-list-tile>
+
+      <v-list-tile v-show="showFetchError">
+        <v-list-tile-content>
+          <v-list-tile-title class="fetch-error">
+            <v-icon
+              small>
+              warning
+            </v-icon>
+            Failed to load this user repositories
```
Comment (paragonHex) [inline frontend/components/RepositoryList.vue]: typo: *users

File: frontend/components/RepositoryList.vue [hunk 2]
```diff
@@ -49,19 +62,33 @@
...
       </v-list-tile>
+
+      <v-list-tile v-show="showFetchError">
+        <v-list-tile-content>
+          <v-list-tile-title class="fetch-error">
+            <v-icon
+              small>
+              warning
+            </v-icon>
+            Failed to load this user contributions
```
Comment (paragonHex) [inline frontend/components/RepositoryList.vue]: typo: *users
